const initialBooks = [
  {
    id: 1700000000001,
    title: "Bumi Manusia",
    author: "Pramoedya Ananta Toer",
    category: "Sejarah",
    year: 1980,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000002,
    title: "Laskar Pelangi",
    author: "Andrea Hirata",
    category: "Fiksi",
    year: 2005,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000003,
    title: "Negeri 5 Menara",
    author: "Ahmad Fuadi",
    category: "Pengembangan Diri",
    year: 2009,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000004,
    title: "Cantik Itu Luka",
    author: "Eka Kurniawan",
    category: "Fiksi",
    year: 2002,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000005,
    title: "Pulang",
    author: "Tere Liye",
    category: "Fiksi",
    year: 2016,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000006,
    title: "Habis Gelap Terbitlah Terang",
    author: "R.A. Kartini",
    category: "Biografi",
    year: 1911,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000007,
    title: "Sapiens: Riwayat Singkat Umat Manusia",
    author: "Yuval Noah Harari",
    category: "Sains",
    year: 2011,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000008,
    title: "Filosofi Teras",
    author: "Henry Manampiring",
    category: "Pengembangan Diri",
    year: 2018,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000009,
    title: "Gadis Kretek",
    author: "Ratih Kumala",
    category: "Fiksi",
    year: 2012,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000010,
    title: "Clean Code",
    author: "Robert C. Martin",
    category: "Teknologi",
    year: 2008,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000011,
    title: "The Pragmatic Programmer",
    author: "Andrew Hunt",
    category: "Teknologi",
    year: 1999,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000012,
    title: "Laut Bercerita",
    author: "Leila S. Chudori",
    category: "Sejarah",
    year: 2017,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000013,
    title: "Atomic Habits",
    author: "James Clear",
    category: "Pengembangan Diri",
    year: 2018,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000014,
    title: "Dilan: 1990",
    author: "Pidi Baiq",
    category: "Drama",
    year: 2014,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000015,
    title: "Ayat-Ayat Cinta",
    author: "Habiburrahman El Shirazy",
    category: "Fiksi",
    year: 2004,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000016,
    title: "Max Havelaar",
    author: "Multatuli",
    category: "Sejarah",
    year: 1860,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000017,
    title: "The Design of Everyday Things",
    author: "Don Norman",
    category: "Teknologi",
    year: 1988,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000018,
    title: "Gus Dur: Biografi",
    author: "Greg Barton",
    category: "Biografi",
    year: 2002,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000019,
    title: "Cosmos",
    author: "Carl Sagan",
    category: "Sains",
    year: 1980,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000020,
    title: "Supernova 1",
    author: "Dee Lestari",
    category: "Fiksi",
    year: 2001,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000021,
    title: "Seni Bersikap Bodo Amat",
    author: "Mark Manson",
    category: "Pengembangan Diri",
    year: 2016,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000022,
    title: "Perahu Kertas",
    author: "Dee Lestari",
    category: "Fiksi",
    year: 2009,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000023,
    title: "Tenggelamnya Kapal Van der Wijck",
    author: "Hamka",
    category: "Fiksi",
    year: 1938,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000024,
    title: "Olenka",
    author: "Budi Darma",
    category: "Fiksi",
    year: 1983,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000025,
    title: "Soekarno: Otobiografi",
    author: "Cindy Adams",
    category: "Biografi",
    year: 1965,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000026,
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    category: "Sains",
    year: 1988,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000027,
    title: "Refactoring",
    author: "Martin Fowler",
    category: "Teknologi",
    year: 1999,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000028,
    title: "Hujan",
    author: "Tere Liye",
    category: "Fiksi",
    year: 2016,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000029,
    title: "Man's Search for Meaning",
    author: "Viktor E. Frankl",
    category: "Pengembangan Diri",
    year: 1946,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000030,
    title: "Catatan Demonstran",
    author: "Soe Hok Gie",
    category: "Biografi",
    year: 1983,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000031,
    title: "Brave New World",
    author: "Aldous Huxley",
    category: "Fiksi",
    year: 1932,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000032,
    title: "The Selfish Gene",
    author: "Richard Dawkins",
    category: "Sains",
    year: 1976,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000033,
    title: "Design Patterns",
    author: "Erich Gamma",
    category: "Teknologi",
    year: 1994,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000034,
    title: "Ronggeng Dukuh Paruk",
    author: "Ahmad Tohari",
    category: "Fiksi",
    year: 1982,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000035,
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    category: "Pengembangan Diri",
    year: 2011,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000036,
    title: "Steve Jobs",
    author: "Walter Isaacson",
    category: "Biografi",
    year: 2011,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000037,
    title: "Babad Tanah Jawi",
    author: "Various",
    category: "Sejarah",
    year: 1600,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000038,
    title: "Gitanjali",
    author: "Rabindranath Tagore",
    category: "Drama",
    year: 1910,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000039,
    title: "The Lean Startup",
    author: "Eric Ries",
    category: "Teknologi",
    year: 2011,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000040,
    title: "1984",
    author: "George Orwell",
    category: "Fiksi",
    year: 1949,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000041,
    title: "The Power of Now",
    author: "Eckhart Tolle",
    category: "Pengembangan Diri",
    year: 1997,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000042,
    title: "Saman",
    author: "Ayu Utami",
    category: "Fiksi",
    year: 1998,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000043,
    title: "A Man Called Ahok",
    author: "Rudi Valinka",
    category: "Biografi",
    year: 2016,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000044,
    title: "The Structure of Scientific Revolutions",
    author: "Thomas S. Kuhn",
    category: "Sains",
    year: 1962,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000045,
    title: "Komet",
    author: "Tere Liye",
    category: "Fiksi",
    year: 2018,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000046,
    title: "Don't Make Me Think",
    author: "Steve Krug",
    category: "Teknologi",
    year: 2000,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000047,
    title: "Madilog",
    author: "Tan Malaka",
    category: "Sejarah",
    year: 1943,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000048,
    title: "Hamlet",
    author: "William Shakespeare",
    category: "Drama",
    year: 1603,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000049,
    title: "The 7 Habits of Highly Effective People",
    author: "Stephen Covey",
    category: "Pengembangan Diri",
    year: 1989,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000050,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    category: "Fiksi",
    year: 1960,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000051,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    category: "Fiksi",
    year: 1951,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000052,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    category: "Fiksi",
    year: 1813,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000053,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    category: "Fiksi",
    year: 1925,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000054,
    title: "Moby Dick",
    author: "Herman Melville",
    category: "Fiksi",
    year: 1851,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000055,
    title: "War and Peace",
    author: "Leo Tolstoy",
    category: "Sejarah",
    year: 1869,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000056,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    category: "Fiksi",
    year: 1937,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000057,
    title: "One Hundred Years of Solitude",
    author: "Gabriel Garcia Marquez",
    category: "Fiksi",
    year: 1967,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000058,
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    category: "Fiksi",
    year: 1954,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000059,
    title: "The Alchemist",
    author: "Paulo Coelho",
    category: "Fiksi",
    year: 1988,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000060,
    title: "The Diary of a Young Girl",
    author: "Anne Frank",
    category: "Biografi",
    year: 1947,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000061,
    title: "The Little Prince",
    author: "Antoine de Saint-Exupéry",
    category: "Fiksi",
    year: 1943,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000062,
    title: "The Chronicles of Narnia",
    author: "C.S. Lewis",
    category: "Fiksi",
    year: 1950,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000063,
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    category: "Fiksi",
    year: 2003,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000064,
    title: "The Hunger Games",
    author: "Suzanne Collins",
    category: "Fiksi",
    year: 2008,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000065,
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    category: "Fiksi",
    year: 1997,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000066,
    title: "The Da Vinci Code",
    author: "Dan Brown",
    category: "Fiksi",
    year: 2003,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000067,
    title: "The Girl with the Dragon Tattoo",
    author: "Stieg Larsson",
    category: "Fiksi",
    year: 2005,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000068,
    title: "The Fault in Our Stars",
    author: "John Green",
    category: "Drama",
    year: 2012,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000069,
    title: "The Martian",
    author: "Andy Weir",
    category: "Sains",
    year: 2011,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000070,
    title: "Gone Girl",
    author: "Gillian Flynn",
    category: "Fiksi",
    year: 2012,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000071,
    title: "The Help",
    author: "Kathryn Stockett",
    category: "Sejarah",
    year: 2009,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000072,
    title: "Life of Pi",
    author: "Yann Martel",
    category: "Fiksi",
    year: 2001,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000073,
    title: "The Road",
    author: "Cormac McCarthy",
    category: "Fiksi",
    year: 2006,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000074,
    title: "The Shining",
    author: "Stephen King",
    category: "Fiksi",
    year: 1977,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000075,
    title: "The Stand",
    author: "Stephen King",
    category: "Fiksi",
    year: 1978,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000076,
    title: "It",
    author: "Stephen King",
    category: "Fiksi",
    year: 1986,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000077,
    title: "The Green Mile",
    author: "Stephen King",
    category: "Fiksi",
    year: 1996,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000078,
    title: "Misery",
    author: "Stephen King",
    category: "Fiksi",
    year: 1987,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000079,
    title: "Pet Sematary",
    author: "Stephen King",
    category: "Fiksi",
    year: 1983,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000080,
    title: "The Dark Tower: The Gunslinger",
    author: "Stephen King",
    category: "Fiksi",
    year: 1982,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000081,
    title: "The Talisman",
    author: "Stephen King",
    category: "Fiksi",
    year: 1984,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000082,
    title: "The Outsider",
    author: "Stephen King",
    category: "Fiksi",
    year: 2018,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000083,
    title: "11/22/63",
    author: "Stephen King",
    category: "Fiksi",
    year: 2011,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000084,
    title: "Under the Dome",
    author: "Stephen King",
    category: "Fiksi",
    year: 2009,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000085,
    title: "Doctor Sleep",
    author: "Stephen King",
    category: "Fiksi",
    year: 2013,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000086,
    title: "The Institute",
    author: "Stephen King",
    category: "Fiksi",
    year: 2019,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000087,
    title: "Fairy Tale",
    author: "Stephen King",
    category: "Fiksi",
    year: 2022,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000088,
    title: "Billy Summers",
    author: "Stephen King",
    category: "Fiksi",
    year: 2021,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000089,
    title: "Later",
    author: "Stephen King",
    category: "Fiksi",
    year: 2021,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000090,
    title: "The Body",
    author: "Stephen King",
    category: "Fiksi",
    year: 1982,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000091,
    title: "Rita Hayworth and Shawshank Redemption",
    author: "Stephen King",
    category: "Fiksi",
    year: 1982,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000092,
    title: "The Long Walk",
    author: "Stephen King",
    category: "Fiksi",
    year: 1979,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000093,
    title: "Rage",
    author: "Stephen King",
    category: "Fiksi",
    year: 1977,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000094,
    title: "The Running Man",
    author: "Stephen King",
    category: "Fiksi",
    year: 1982,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000095,
    title: "Thinner",
    author: "Stephen King",
    category: "Fiksi",
    year: 1984,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000096,
    title: "The Regulators",
    author: "Stephen King",
    category: "Fiksi",
    year: 1996,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000097,
    title: "Desperation",
    author: "Stephen King",
    category: "Fiksi",
    year: 1996,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000098,
    title: "Bag of Bones",
    author: "Stephen King",
    category: "Fiksi",
    year: 1998,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000099,
    title: "The Girl Who Loved Tom Gordon",
    author: "Stephen King",
    category: "Fiksi",
    year: 1999,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000100,
    title: "Dreamcatcher",
    author: "Stephen King",
    category: "Fiksi",
    year: 2001,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000101,
    title: "The Colour of Magic",
    author: "Terry Pratchett",
    category: "Fiksi",
    year: 1983,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000102,
    title: "Mort",
    author: "Terry Pratchett",
    category: "Fiksi",
    year: 1987,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000103,
    title: "Guards! Guards!",
    author: "Terry Pratchett",
    category: "Fiksi",
    year: 1989,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000104,
    title: "Reaper Man",
    author: "Terry Pratchett",
    category: "Fiksi",
    year: 1991,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000105,
    title: "Small Gods",
    author: "Terry Pratchett",
    category: "Fiksi",
    year: 1992,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000106,
    title: "Night Watch",
    author: "Terry Pratchett",
    category: "Fiksi",
    year: 2002,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000107,
    title: "The Wee Free Men",
    author: "Terry Pratchett",
    category: "Fiksi",
    year: 2003,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000108,
    title: "Going Postal",
    author: "Terry Pratchett",
    category: "Fiksi",
    year: 2004,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000109,
    title: "Thud!",
    author: "Terry Pratchett",
    category: "Fiksi",
    year: 2005,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000110,
    title: "Making Money",
    author: "Terry Pratchett",
    category: "Fiksi",
    year: 2007,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000111,
    title: "Unseen Academicals",
    author: "Terry Pratchett",
    category: "Fiksi",
    year: 2009,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000112,
    title: "I Shall Wear Midnight",
    author: "Terry Pratchett",
    category: "Fiksi",
    year: 2010,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000113,
    title: "Snuff",
    author: "Terry Pratchett",
    category: "Fiksi",
    year: 2011,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000114,
    title: "Raising Steam",
    author: "Terry Pratchett",
    category: "Fiksi",
    year: 2013,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000115,
    title: "The Shepherd's Crown",
    author: "Terry Pratchett",
    category: "Fiksi",
    year: 2015,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000116,
    title: "Good Omens",
    author: "Neil Gaiman, Terry Pratchett",
    category: "Fiksi",
    year: 1990,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000117,
    title: "American Gods",
    author: "Neil Gaiman",
    category: "Fiksi",
    year: 2001,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000118,
    title: "Coraline",
    author: "Neil Gaiman",
    category: "Fiksi",
    year: 2002,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000119,
    title: "The Graveyard Book",
    author: "Neil Gaiman",
    category: "Fiksi",
    year: 2008,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
  {
    id: 1700000000120,
    title: "The Ocean at the End of the Lane",
    author: "Neil Gaiman",
    category: "Fiksi",
    year: 2013,
    isBorrowed: false,
    borrowerName: "",
    borrowDate: "",
    dueDate: "",
    history: [],
  },
];
